### ISSUE TITLE
random removed

### ISSUE THREAD

**Issue by bourne9** [urShadow/FakeOnline#1]
Why did you remove random() ?

I used to make the player count less suspicious, now that has been removed, it will easily get caught by the SA-MP team. That random function was fucking amazing.

Add it back like this - SetFakeOnline() + random();

**Comment by urShadow** [comment]
Use this:
```pawn
forward UpdateFakeOnline();

public UpdateFakeOnline()
{
   SetFakeOnline(96 + random(5));
}

public OnGameModeInit()
{
	SetTimer("UpdateFakeOnline", 1000, true);
}
```

**Comment by bourne9** [comment]
Where the updated .dll and .so files ?
